### ISSUE TITLE
wisc.edu CCSO server

### ISSUE THREAD

**Issue by dotcomboom** [michael-lazar/ccso-nameserver#2]
Not quite an issue, but after trying some of the hosts in [the "sites" help topic](https://github.com/michael-lazar/ccso-nameserver/blob/master/qi/help/native/sites), it turns out that the University of Wisconsin-Madison's CCSO/ph server is still online! Queries can be made still as well. Wonder if the database is still being updated.
![image](https://user-images.githubusercontent.com/38927017/55764217-48ee0800-5a30-11e9-8c04-b5299f69ec25.png)

**Comment by michael-lazar** [comment]
I found that too! I was quite surprised, I couldn't find *anything* searching on google when I started this project. It looks like it's an active mirror for their white pages database. https://kb.wisc.edu/page.php?id=4418

I also discovered that MIT still has a nameserver!

cso://mitdir.mit.edu:105
http://www.mit.edu/mitdir-help.html

I've been compiling a list here: gopher://mozz.us/1/ccso/servers

I would be very appreciative if anyone has any more information on CCSO servers that are still running in the wild.
