### ISSUE TITLE
Permission denied when trying to build Dockerfile

### ISSUE THREAD

**Issue by mariteaux** [michael-lazar/ccso-nameserver#3]
I'm trying to get a CCSO server going on Raspbian, and while I got Docker working alright, when I get most of the way through trying to build the Dockerfile, I get a "permission denied" error on the install script and the build halts:
```
make[1]: Leaving directory `/opt/nameserv/source/phquery'
cd include; make install
make[1]: Entering directory `/opt/nameserv/source/include'
mkdir /usr/local/include
mkdir: cannot create directory '/usr/local/include': File exists
make[1]: [install] Error 1 (ignored)
/opt/nameserv/source/bin/install.sh -c -m 444 -o root -g  root qiapi.h /usr/local/include
make[1]: execvp: /opt/nameserv/source/bin/install.sh: Permission denied
make[1]: *** [install] Error 127
make[1]: Leaving directory `/opt/nameserv/source/include'
make: *** [install] Error 2
The command '/bin/sh -c make install' returned a non-zero code: 2
```

I was thinking this was something due to the pi user not being a part of the docker group, but it doesn't seem to make much of a difference. Any idea what I'm doing wrong?

**Comment by michael-lazar** [comment]
Hmm, I apologize but I'm not exactly sure what's going on here. It works on my machine after cloning a fresh copy of the repository and running the ``./ccso build`` command. I've tested on both macOS and CentOS host machines.

**Comment by mariteaux** [comment]
Damn. Do you know of any other CCSO server software I can try maybe, or any way to run Qi outside of the container?

**Comment by michael-lazar** [comment]
Sadly I do not, that's why I created this repository in the first place!

If you want to try running outside of the container, you might be able to get pretty far by running the steps in the [Dockerfile](https://github.com/michael-lazar/ccso-nameserver/blob/master/Dockerfile) manually. I'm sure some of the dependency package names will have slightly different names on debian, but beyond that it's pretty generic and I assume it will work just as well.

**Comment by mariteaux** [comment]
I'll give it a shot. Don't suppose there's much we can do if it doesn't work, seeing as it's working fine for you and I'm really not a *nix guy. I guess it's something funny with Docker on Raspbian, they don't let you do the full setup on there, or again, weird permissions things (though aren't things run as root inside containers anyway? Not sure why I'd be getting a permissions error inside one).

Anyway, I'll let you know if I get it working. Thanks for the repo anyway!
